"""Dataset contracts, units, aliases, and research presets."""


FAMILY_CONTRACTS = {
    "wells": {
        "identifiers": ("API_WELL_NUMBER",),
        "units": {"WATER_DEPTH": "ft", "BH_TOTAL_MD": "ft"},
        "aliases": {"api": "API_WELL_NUMBER", "operator": "COMPANY_NAME"},
    },
    "production": {
        "identifiers": ("Api Well Number", "Completion Name"),
        "units": {
            "Monthly Oil Volume": "bbl",
            "Monthly Gas Volume": "mcf",
            "Monthly Water Volume": "bbl",
        },
        "aliases": {
            "oil_volume": "Monthly Oil Volume",
            "gas_volume": "Monthly Gas Volume",
            "water_volume": "Monthly Water Volume",
        },
    },
    "regulatory": {
        "identifiers": ("API_WELL_NUMBER", "SN_WAR"),
        "units": {},
        "aliases": {"api": "API_WELL_NUMBER", "report_id": "SN_WAR"},
    },
    "casing": {
        "identifiers": ("SN_APD_FK", "SN_WAR_FK"),
        "units": {
            "CASING_SIZE": "in",
            "CASING_WEIGHT": "lb/ft",
            "CASING_SECTION_MD": "ft",
            "CSNG_SETTING_BOTM_MD": "ft",
        },
        "aliases": {"casing_size": "CASING_SIZE", "bottom_md": "CASING_SECTION_MD"},
    },
    "trajectory": {
        "identifiers": ("API Number",),
        "units": {"MD": "ft", "TVD": "ft", "DLS": "deg/100ft"},
        "aliases": {"api": "API Number", "horizontal_departure": "calc_max_horizontal_departure_ft"},
    },
    "wellbore": {
        "identifiers": ("API_WELL_NUMBER",),
        "units": {"BHTST_PRESSURE": "psi", "BHTST_MD": "ft", "BHTST_TVD": "ft"},
        "aliases": {"api": "API_WELL_NUMBER"},
    },
    "applications": {
        "identifiers": ("API_WELL_NUMBER", "SN_APD", "application_id"),
        "units": {},
        "aliases": {"api": "API_WELL_NUMBER", "application": "application_id"},
    },
    "documents": {
        "identifiers": ("API_WELL_NUMBER", "API", "DOC_ID", "document_id"),
        "units": {"FILE_SIZE": "source units"},
        "aliases": {"api": "API_WELL_NUMBER", "document": "DOC_ID"},
    },
    "approvals": {
        "identifiers": ("approval_event_id", "approval_group_id", "asset_identifier"),
        "units": {},
        "aliases": {"asset": "asset_identifier", "approval": "approval_event_id"},
    },
    "platforms": {
        "identifiers": ("COMPLEX_ID_NUM", "STRUCTURE_NUMBER"),
        "units": {"WATER_DEPTH": "ft"},
        "aliases": {"complex_id": "COMPLEX_ID_NUM", "structure": "STRUCTURE_NUMBER"},
    },
    "pipelines": {
        "identifiers": ("segment_number",),
        "units": {"segment_length_ft": "ft", "max_water_depth_ft": "ft", "maop_psi": "psi"},
        "aliases": {"segment": "segment_number", "company": "operator_name"},
    },
    "decommissioning": {
        "identifiers": ("API_WELL_NUMBER", "LEASE_NUMBER", "AUTH_NUMBER"),
        "units": {"P50_COST": "USD", "P70_COST": "USD", "P90_COST": "USD"},
        "aliases": {"api": "API_WELL_NUMBER", "lease": "LEASE_NUMBER"},
    },
    "leases": {
        "identifiers": ("LEASE_NUMBER",),
        "units": {"ASSIGNMENT_PCT": "pct", "CURRENT_AREA": "acres"},
        "aliases": {"lease": "LEASE_NUMBER", "assignment_pct": "ASSIGNMENT_PCT"},
    },
    "companies": {
        "identifiers": ("MMS_COMPANY_NUM",),
        "units": {},
        "aliases": {"company_number": "MMS_COMPANY_NUM", "company": "BUS_ASC_NAME"},
    },
    "logging": {
        "identifiers": ("API_WELL_NUMBER",),
        "units": {"TOP_MD": "ft", "BOTTOM_MD": "ft"},
        "aliases": {"api": "API_WELL_NUMBER"},
    },
}


def _dataset(
    filename: str,
    family: str,
    required_columns: tuple[str, ...] = (),
    *,
    required: bool = False,
) -> dict:
    contract = FAMILY_CONTRACTS.get(
        family,
        {"identifiers": (), "units": {}, "aliases": {}},
    )
    return {
        "filename": filename,
        "family": family,
        "required_columns": required_columns,
        "identifiers": contract["identifiers"],
        "units": contract["units"],
        "aliases": contract["aliases"],
        "required": required,
    }


DATASET_CATALOG = {
    "boreholes": _dataset(
        "df_boreholes.parquet",
        "wells",
        ("API_WELL_NUMBER", "WELL_NAME", "COMPANY_NAME"),
        required=True,
    ),
    "production": _dataset(
        "df_gom_production.parquet",
        "production",
        ("Api Well Number", "Production Date", "Monthly Oil Volume"),
        required=True,
    ),
    "war_main": _dataset(
        "df_WAR_main.parquet",
        "regulatory",
        ("SN_WAR", "API_WELL_NUMBER"),
        required=True,
    ),
    "war_text": _dataset(
        "df_WAR.parquet",
        "regulatory",
        ("SN_WAR", "TEXT_REMARK"),
        required=True,
    ),
    "war_tubular": _dataset("df_mv_war_tubular_summaries.parquet", "casing"),
    "war_tubular_prop": _dataset("df_mv_war_tubular_summaries_prop.parquet", "casing"),
    "points": _dataset("df_points.parquet", "trajectory"),
    "azimuth": _dataset(
        "df_azimuth.parquet",
        "trajectory",
        ("API Number", "MD", "TVD"),
        required=True,
    ),
    "wellpath_metrics": _dataset(
        "df_wellpath_metrics.parquet",
        "trajectory",
        ("API Number", "metric_status"),
        required=True,
    ),
    "directional_surveys": _dataset("df_directional_surveys.parquet", "trajectory"),
    "bhp": _dataset("df_bhp_survey.parquet", "wellbore"),
    "well_potential_tests": _dataset("df_well_potential_tests.parquet", "wellbore"),
    "api_changes": _dataset("df_api_changes.parquet", "wellbore"),
    "api_well_completions": _dataset("df_api_well_completions.parquet", "wellbore"),
    "eor_main": _dataset("df_eor_mv_eor_mainquery.parquet", "wellbore"),
    "eor_main_prop": _dataset("df_eor_mv_eor_mainquery_prop.parquet", "wellbore"),
    "eor_geomarkers": _dataset("df_eor_mv_eor_geomarkers.parquet", "wellbore"),
    "eor_completions": _dataset("df_eor_mv_eor_completions.parquet", "wellbore"),
    "eor_completions_prop": _dataset("df_eor_mv_eor_completionsprop.parquet", "wellbore"),
    "eor_comp_status_codes": _dataset("df_eor_mv_eor_compstatcodes.parquet", "wellbore"),
    "eor_cut_casings": _dataset("df_eor_mv_eor_cut_casings.parquet", "wellbore"),
    "eor_hcbearing_completions": _dataset(
        "df_eor_mv_eor_hcbearing_intvl_comps.parquet",
        "wellbore",
    ),
    "eor_hydrocarbon_types": _dataset("df_eor_mv_eor_hydrobarbtypecodes.parquet", "wellbore"),
    "eor_operation_codes": _dataset("df_eor_mv_eor_operationcodes.parquet", "wellbore"),
    "eor_perf": _dataset("df_eor_mv_eor_perf_intervals.parquet", "wellbore"),
    "apd_main": _dataset(
        "df_apd_main.parquet",
        "applications",
        ("SN_APD", "API_WELL_NUMBER"),
        required=True,
    ),
    "apd_main_prop": _dataset("df_apd_main_prop.parquet", "applications"),
    "apd_attachments": _dataset("df_apd_attachments.parquet", "applications"),
    "apd_geologic": _dataset("df_apd_geologic.parquet", "applications"),
    "apd_questions": _dataset("df_apd_questions.parquet", "applications"),
    "apd_question_responses": _dataset("df_apd_question_responses.parquet", "applications"),
    "apd_casing_intervals": _dataset(
        "df_apd_casing_intervals.parquet",
        "casing",
        ("SN_APD_FK", "SN_APD_CSG_INTV"),
        required=True,
    ),
    "apd_casing_sections": _dataset(
        "df_apd_casing_sectons.parquet",
        "casing",
        ("SN_APD_CSNG_INTV_FK",),
        required=True,
    ),
    "apm_applications": _dataset("df_apm_applications.parquet", "applications"),
    "apm_events": _dataset("df_apm_events.parquet", "applications"),
    "apm_main_prop_narrative": _dataset(
        "df_apm_main_prop_narrative.parquet",
        "applications",
    ),
    "apm_preventers": _dataset("df_apm_preventers.parquet", "applications"),
    "apm_questions": _dataset("df_apm_questions.parquet", "applications"),
    "apm_question_responses": _dataset("df_apm_question_responses.parquet", "applications"),
    "apm_resubmittals": _dataset("df_apm_resubmittals.parquet", "applications"),
    "apm_suboperations": _dataset("df_apm_suboperations.parquet", "applications"),
    "apm_verbals": _dataset("df_apm_verbals.parquet", "applications"),
    "application_attachments": _dataset("df_application_attachments.parquet", "documents"),
    "open_hole_runs": _dataset("df_open_hole_runs.parquet", "logging"),
    "open_hole_tools": _dataset("df_open_hole_tools.parquet", "logging"),
    "attachments": _dataset(
        "df_apd_apm_att.parquet",
        "documents",
        ("API_WELL_NUMBER", "ATT_NAME", "Source"),
        required=True,
    ),
    "frs": _dataset(
        "df_frs_files_list.parquet",
        "documents",
        ("API", "DOC_ID"),
        required=True,
    ),
    "asset_approvals": _dataset("df_asset_approval_events.parquet", "approvals"),
    "structures": _dataset(
        "df_gom_structure.parquet",
        "platforms",
        ("AREA_CODE", "BLOCK_NUMBER", "COMPLEX_ID_NUM", "STRUCTURE_NUMBER"),
        required=True,
    ),
    "platform_approvals": _dataset("df_platform_approvals.parquet", "platforms"),
    "platform_removals": _dataset("df_platform_structure_removals.parquet", "platforms"),
    "pipeline_permit_segments": _dataset("df_pipeline_permit_segments.parquet", "pipelines"),
    "pipeline_submittals": _dataset("df_pipeline_submittals.parquet", "pipelines"),
    "decom_estimates": _dataset("df_mv_decom_cost_estimates.parquet", "decommissioning"),
    "decom_inst_pipe": _dataset("df_mv_decom_cost_inst_pipe.parquet", "decommissioning"),
    "decom_inst_plat": _dataset("df_mv_decom_cost_inst_plat.parquet", "decommissioning"),
    "decom_prop_pipe": _dataset("df_mv_decom_cost_prop_pipe.parquet", "decommissioning"),
    "decom_prop_plat": _dataset("df_mv_decom_cost_prop_plat.parquet", "decommissioning"),
    "decom_prop_well": _dataset("df_mv_decom_cost_prop_well.parquet", "decommissioning"),
    "decom_spud_well": _dataset("df_mv_decom_cost_spud_well.parquet", "decommissioning"),
    "decom_totals": _dataset("df_mv_decom_cost_totals.parquet", "decommissioning"),
    "lease_data": _dataset(
        "df_lease_data.parquet",
        "leases",
        ("LEASE_NUMBER",),
        required=True,
    ),
    "lease_list": _dataset("df_lease_list.parquet", "leases"),
    "lease_owner": _dataset("df_lease_owner.parquet", "leases"),
    "lease_owner_designated_operator": _dataset(
        "df_lease_owner_designated_operator.parquet",
        "leases",
    ),
    "lease_owner_remarks": _dataset("df_lease_owner_remarks.parquet", "leases"),
    "lease_remarks": _dataset("df_lease_remarks.parquet", "leases"),
    "lease_descriptions": _dataset("df_lease_descriptions.parquet", "leases"),
    "company_all": _dataset(
        "df_company_all.parquet",
        "companies",
        ("MMS_COMPANY_NUM", "BUS_ASC_NAME"),
        required=True,
    ),
}

DATASETS = {
    key: value["filename"]
    for key, value in DATASET_CATALOG.items()
}

MIN_REQUIRED_DATASETS = [
    key
    for key, value in DATASET_CATALOG.items()
    if value["required"]
]

INCIDENT_TERMS = {
    "stuck-pipe": [
        "stuck pipe",
        "stuck drill pipe",
        "stuck bha",
        "stuck string",
        "jarred",
        "fishing",
        "washover",
        "overshot",
    ],
    "lost-circulation": ["lost circulation", "losses", "lost returns", "lc material", "lcm", "seepage loss"],
    "kick": ["kick", "well control", "flow check", "shut in", "sidpp", "sicp"],
    "fishing": ["fish", "fishing", "overshot", "spear", "junk basket", "washover", "milling"],
    "cementing": ["cement", "squeeze", "plug", "shoe test", "liner test"],
    "logging": ["wireline", "mwd", "lwd", "log", "gamma ray", "resistivity"],
}

PRODUCTION_GROUP_ALIASES = {
    "completion_name": ("completion_name", "Completion Name"),
    "completion": ("completion_name", "Completion Name"),
    "product_code": ("product_code", "Product Code"),
    "product": ("product_code", "Product Code"),
    "production_interval_code": ("production_interval_code", "Production Interval Code"),
    "interval_code": ("production_interval_code", "Production Interval Code"),
    "interval": ("production_interval_code", "Production Interval Code"),
    "interval_code_name": ("production_interval_code", "Production Interval Code"),
}

PRODUCTION_UNITS = {
    "Monthly Oil Volume": "bbl",
    "Monthly Gas Volume": "mcf",
    "Monthly Water Volume": "bbl",
    "Injection Volume": "bbl",
    "Monthly Oil Volume_m3": "m3",
    "Monthly Gas Volume_mcf": "mcf",
    "Monthly Gas Volume_m3": "m3",
    "Monthly Water Volume_m3": "m3",
    "Injection Volume_m3": "m3",
    "Days On Prod": "days",
    "oil_volume": "bbl",
    "gas_volume": "mcf",
    "water_volume": "bbl",
    "injection_volume": "bbl",
    "days_on_prod": "days",
    "oil_rate": "bbl/day",
    "gas_rate": "mcf/day",
    "water_rate": "bbl/day",
    "Day_Aver_Oil_bbl_per_day": "bbl/day",
    "Day_Aver_Water_bbl_per_day": "bbl/day",
    "Day_Aver_Gas_mcf_per_day": "mcf/day",
    "Day_Aver_Oil": "bbl/day",
    "Day_Aver_Water": "bbl/day",
    "Day_Aver_Gas": "mcf/day",
}

PRODUCTION_TIME_SERIES_METRICS = [
    {"field": "oil_volume", "source_column": "Monthly Oil Volume", "aggregation": "sum", "unit": "bbl"},
    {"field": "gas_volume", "source_column": "Monthly Gas Volume", "aggregation": "sum", "unit": "mcf"},
    {"field": "water_volume", "source_column": "Monthly Water Volume", "aggregation": "sum", "unit": "bbl"},
    {"field": "injection_volume", "source_column": "Injection Volume", "aggregation": "sum", "unit": "bbl"},
    {"field": "days_on_prod", "source_column": "Days On Prod", "aggregation": "sum", "unit": "days"},
    {
        "field": "oil_rate",
        "source_column": "Monthly Oil Volume / Days On Prod",
        "aggregation": "derived",
        "unit": "bbl/day",
    },
    {
        "field": "gas_rate",
        "source_column": "Monthly Gas Volume / Days On Prod",
        "aggregation": "derived",
        "unit": "mcf/day",
    },
    {
        "field": "water_rate",
        "source_column": "Monthly Water Volume / Days On Prod",
        "aggregation": "derived",
        "unit": "bbl/day",
    },
]

BOREHOLE_UNITS = {
    "BH_TOTAL_MD": "ft",
    "BH_TOTAL_MD_M": "m",
    "WELL_BORE_TVD": "ft",
    "WELL_BORE_TVD_M": "m",
    "WELL_TD_SS": "ft",
    "WATER_DEPTH": "ft",
    "WATER_DEPTH_M": "m",
    "RKB_ELEVATION": "ft",
    "RKB_ELEVATION_M": "m",
    "SURF_LATITUDE": "deg",
    "SURF_LONGITUDE": "deg",
    "BOTM_LATITUDE": "deg",
    "BOTM_LONGITUDE": "deg",
}

TRAJECTORY_UNITS = {
    "Survey Point MD": "ft",
    "Survey Point TVD": "ft",
    "Survey Point neg TVD": "ft",
    "Delta X": "ft",
    "Delta Y": "ft",
    "easting": "ft Web Mercator legacy alias",
    "northing": "ft Web Mercator legacy alias",
    "webmerc_easting_ft": "ft Web Mercator",
    "webmerc_northing_ft": "ft Web Mercator",
    "Latitude": "deg",
    "Longitude": "deg",
    "Incl Ang Deg Val": "deg",
    "Incl Ang Min Val": "arcmin",
    "Dir Deg Val": "deg",
    "Dir Mins Val": "arcmin",
    "horizontal_distance_ft": "ft",
    "first_tvd_ft": "ft",
    "final_tvd_ft": "ft",
    "tvd_delta_ft": "ft",
    "delta_easting_ft": "ft",
    "delta_northing_ft": "ft",
    "coordinate_basis": "text",
}

WELLPATH_METRICS_UNITS = {
    "source_horizontal_distance_ft": "ft",
    "source_endpoint_east_offset_ft": "ft",
    "source_endpoint_north_offset_ft": "ft",
    "source_closure_azimuth_deg": "deg",
    "source_max_horizontal_departure_ft": "ft",
    "source_max_departure_md": "ft",
    "source_md_delta_ft": "ft",
    "source_tvd_delta_ft": "ft",
    "source_horizontal_tvd_ratio": "ratio",
    "source_min_md_spacing_ft": "ft",
    "source_median_md_spacing_ft": "ft",
    "calc_horizontal_distance_ft": "ft",
    "calc_endpoint_east_offset_ft": "ft",
    "calc_endpoint_north_offset_ft": "ft",
    "calc_closure_azimuth_deg": "deg",
    "calc_max_horizontal_departure_ft": "ft",
    "calc_max_departure_md": "ft",
    "calc_md_delta_ft": "ft",
    "calc_tvd_delta_ft": "ft",
    "calc_horizontal_tvd_ratio": "ratio",
    "calc_min_md_spacing_ft": "ft",
    "calc_median_md_spacing_ft": "ft",
    "calc_max_inclination_deg": "deg",
    "calc_avg_inclination_deg": "deg",
    "calc_final_inclination_deg": "deg",
    "calc_first_md_over_60deg": "ft",
    "calc_first_md_over_80deg": "ft",
    "calc_lateral_length_over_80deg_ft": "ft",
    "calc_max_dls_deg_per_100ft": "deg/100ft",
    "calc_avg_dls_deg_per_100ft": "deg/100ft",
    "calc_p95_dls_deg_per_100ft": "deg/100ft",
    "calc_cumulative_dogleg_deg": "deg",
    "horizontal_distance_diff_ft": "ft",
    "source_calc_hd_diff_pct": "pct",
    "horizontal_tvd_ratio_diff": "ratio",
    "source_first_md": "ft",
    "source_last_md": "ft",
    "calc_first_md": "ft",
    "calc_last_md": "ft",
}

AZIMUTH_DLS_UNITS = {
    "MD": "ft",
    "Deviation Angle": "deg",
    "Azimuth": "deg",
    "DLS": "deg/100ft",
    "MD_Diff": "ft",
    "min_step_ft": "ft",
    "max_deviation_deg": "deg",
    "max_dls_deg_per_100ft": "deg/100ft",
    "avg_dls_deg_per_100ft": "deg/100ft",
    "calculated_horizontal_distance_ft": "ft",
    "calculated_final_tvd_ft": "ft",
    "Calc_TVD_ft": "ft",
    "Calc_Easting_offset_ft": "ft",
    "Calc_Northing_offset_ft": "ft",
}

EARTH_RADIUS_FT = 6378137 * 3.28084

CASING_UNITS = {
    "CASING_SIZE": "in",
    "CASING_WEIGHT": "lb/ft",
    "CSNG_HOLESIZE": "in",
    "CSNG_HOLE_SIZE": "in",
    "CSNG_BOP_STACK_SIZE": "in",
    "CSNG_TOP_MD": "ft",
    "CASING_SECTION_MD": "ft",
    "CASING_SECTION_TVD": "ft",
    "CSNG_SETTING_TOP_MD": "ft",
    "CSNG_SETTING_BOTM_MD": "ft",
    "TOP_MD": "ft",
    "BOTTOM_MD": "ft",
    "CASING_BURST_PSI": "psi",
    "CASING_COLLPSE_PSI": "psi",
    "CSNG_LINER_TEST_PRSS": "psi",
    "CSNG_SHOE_TEST_PRSS": "psi",
    "CSNG_WELLHEAD_RATING": "psi",
    "CSNG_ANNULAR_RATING": "psi",
    "CSNG_BOP_RATING": "psi",
    "CSNG_ANNULAR_TEST_PRSS": "psi",
    "CSNG_BOP_DIV_TEST_PRSS": "psi",
    "CSNG_FORMATION_TEST_PRSS": "psi",
    "CSNG_MUD_WGT_PPG": "ppg",
    "CSNG_FRAC_GRAD_PPG": "ppg",
    "CASING_PORE_PRSS_PPG": "ppg",
    "CSNG_CEMENT_VOL": "bbl",
    "max_size": "in",
    "max_depth": "ft",
    "apd_max_depth_ft": "ft",
    "war_max_depth_ft": "ft",
    "max_depth_ft": "ft",
}

BHP_UNITS = {
    "BHTST_MD": "ft",
    "BHTST_TVD": "ft",
    "BHTST_PRESSURE": "psi",
    "BHTST_SI_PRSS": "psi",
    "BHTST_TEMP": "degF",
    "SI_TIME": "hr",
}

EOR_INTERVAL_UNITS = {
    "TOP_MD": "ft",
    "PERF_TOP_MD": "ft",
    "PERF_BASE_MD": "ft",
    "PERF_TOP_TVD": "ft",
    "PERF_BOTM_TVD": "ft",
    "deepest_marker_ft": "ft",
}

DECOM_UNITS = {
    "P50_COST": "USD",
    "P70_COST": "USD",
    "P90_COST": "USD",
    "DTR_COST": "USD",
    "WELL_INST_DCOM_P50": "USD",
    "WELL_INST_DCOM_P70": "USD",
    "WELL_INST_DCOM_P90": "USD",
    "WELL_INST_DCOM_INDTR": "USD",
    "WELL_PRP_DCOM_P50": "USD",
    "WELL_PRP_DCOM_P70": "USD",
    "WELL_PRP_DCOM_P90": "USD",
    "WELL_PRP_DCOM_INDTR": "USD",
    "SEGMENT_DCOM_P50": "USD",
    "SEGMENT_DCOM_P70": "USD",
    "SEGMENT_DCOM_P90": "USD",
    "SEGMENT_DCOM_INDTR": "USD",
    "PLT_REMOVAL_DCOM_P50": "USD",
    "PLT_REMOVAL_DCOM_P70": "USD",
    "PLT_REMOVAL_DCOM_P90": "USD",
    "PLT_REMOVAL_DCOM_INDTR": "USD",
    "PLT_SITE_CLRNC_DCOM_P50": "USD",
    "PLT_SITE_CLRNC_DCOM_P70": "USD",
    "PLT_SITE_CLRNC_DCOM_P90": "USD",
    "PLT_SITE_CLRNC_DCOM_INDTR": "USD",
    "BLK_MAX_WTR_DPTH": "ft",
}

LEASE_UNITS = {
    "ASSIGNMENT_PCT": "pct",
    "Ownership %": "pct",
    "ROYALTY_RATE": "pct",
    "ALIQUOT_AREA": "area as reported by BSEE",
    "CURRENT_AREA": "area as reported by BSEE",
}

TABLE_UNITS = {
    "boreholes": BOREHOLE_UNITS,
    "production": PRODUCTION_UNITS,
    "points": TRAJECTORY_UNITS,
    "azimuth": AZIMUTH_DLS_UNITS,
    "wellpath_metrics": WELLPATH_METRICS_UNITS,
    "bhp": BHP_UNITS,
    "eor_geomarkers": EOR_INTERVAL_UNITS,
    "eor_perf": EOR_INTERVAL_UNITS,
    "apd_casing_intervals": CASING_UNITS,
    "apd_casing_sections": CASING_UNITS,
    "war_tubular": CASING_UNITS,
    "war_tubular_prop": CASING_UNITS,
    "decom_estimates": DECOM_UNITS,
    "decom_spud_well": DECOM_UNITS,
    "decom_totals": DECOM_UNITS,
    "lease_data": LEASE_UNITS,
    "lease_owner": LEASE_UNITS,
    "lease_owner_designated_operator": LEASE_UNITS,
    "lease_owner_remarks": LEASE_UNITS,
}

METRIC_ALIASES = {
    "boreholes": {
        "total_depth": "BH_TOTAL_MD",
        "measured_depth": "BH_TOTAL_MD",
        "tvd": "WELL_BORE_TVD",
        "water_depth": "WATER_DEPTH",
    },
    "production": {
        "production_oil": "Monthly Oil Volume",
        "oil_volume": "Monthly Oil Volume",
        "production_gas": "Monthly Gas Volume",
        "gas_volume": "Monthly Gas Volume",
        "production_water": "Monthly Water Volume",
        "water_volume": "Monthly Water Volume",
        "days_on_prod": "Days On Prod",
    },
    "wellpath_metrics": {
        "horizontal_departure": "calc_max_horizontal_departure_ft",
        "max_horizontal_departure": "calc_max_horizontal_departure_ft",
        "horizontal_distance": "calc_horizontal_distance_ft",
        "source_horizontal_departure": "source_max_horizontal_departure_ft",
        "source_horizontal_distance": "source_horizontal_distance_ft",
        "lateral_length": "calc_lateral_length_over_80deg_ft",
        "max_dls": "calc_max_dls_deg_per_100ft",
        "avg_dls": "calc_avg_dls_deg_per_100ft",
        "trajectory_type": "calc_trajectory_type",
        "closure_azimuth": "calc_closure_azimuth_deg",
        "max_inclination": "calc_max_inclination_deg",
    },
    "decom_spud_well": {
        "decom_cost": "WELL_INST_DCOM_P90",
        "p50_cost": "WELL_INST_DCOM_P50",
        "p70_cost": "WELL_INST_DCOM_P70",
        "p90_cost": "WELL_INST_DCOM_P90",
    },
    "decom_totals": {
        "decom_cost": "P90_COST",
        "p50_cost": "P50_COST",
        "p70_cost": "P70_COST",
        "p90_cost": "P90_COST",
    },
    "lease_data": {
        "royalty_rate": "ROYALTY_RATE",
        "current_area": "CURRENT_AREA",
    },
    "lease_owner": {
        "assignment_pct": "ASSIGNMENT_PCT",
        "ownership_pct": "ASSIGNMENT_PCT",
        "owner_percent": "ASSIGNMENT_PCT",
        "interest_pct": "ASSIGNMENT_PCT",
    },
    "lease_owner_designated_operator": {
        "assignment_pct": "ASSIGNMENT_PCT",
        "ownership_pct": "ASSIGNMENT_PCT",
        "owner_percent": "ASSIGNMENT_PCT",
        "interest_pct": "ASSIGNMENT_PCT",
    },
    "lease_owner_remarks": {
        "assignment_pct": "ASSIGNMENT_PCT",
        "ownership_pct": "ASSIGNMENT_PCT",
        "owner_percent": "ASSIGNMENT_PCT",
        "interest_pct": "ASSIGNMENT_PCT",
    },
}
