"""Static dataset, unit, and alias metadata for well research."""

DATASETS = {
    "boreholes": "df_boreholes.parquet",
    "production": "df_gom_production.parquet",
    "war_main": "df_WAR_main.parquet",
    "war_text": "df_WAR.parquet",
    "war_tubular": "df_mv_war_tubular_summaries.parquet",
    "war_tubular_prop": "df_mv_war_tubular_summaries_prop.parquet",
    "points": "df_points.parquet",
    "azimuth": "df_azimuth.parquet",
    "wellpath_metrics": "df_wellpath_metrics.parquet",
    "bhp": "df_bhp_survey.parquet",
    "eor_main": "df_eor_mv_eor_mainquery.parquet",
    "eor_geomarkers": "df_eor_mv_eor_geomarkers.parquet",
    "eor_completions": "df_eor_mv_eor_completions.parquet",
    "eor_completions_prop": "df_eor_mv_eor_completionsprop.parquet",
    "eor_perf": "df_eor_mv_eor_perf_intervals.parquet",
    "apd_main": "df_apd_main.parquet",
    "apd_casing_intervals": "df_apd_casing_intervals.parquet",
    "apd_casing_sections": "df_apd_casing_sectons.parquet",
    "open_hole_runs": "df_open_hole_runs.parquet",
    "open_hole_tools": "df_open_hole_tools.parquet",
    "attachments": "df_apd_apm_att.parquet",
    "frs": "df_frs_files_list.parquet",
    "decom_estimates": "df_mv_decom_cost_estimates.parquet",
    "decom_inst_pipe": "df_mv_decom_cost_inst_pipe.parquet",
    "decom_inst_plat": "df_mv_decom_cost_inst_plat.parquet",
    "decom_prop_pipe": "df_mv_decom_cost_prop_pipe.parquet",
    "decom_prop_plat": "df_mv_decom_cost_prop_plat.parquet",
    "decom_prop_well": "df_mv_decom_cost_prop_well.parquet",
    "decom_spud_well": "df_mv_decom_cost_spud_well.parquet",
    "decom_totals": "df_mv_decom_cost_totals.parquet",
    "lease_data": "df_lease_data.parquet",
    "lease_list": "df_lease_list.parquet",
    "lease_owner": "df_lease_owner.parquet",
    "lease_owner_designated_operator": "df_lease_owner_designated_operator.parquet",
    "lease_owner_remarks": "df_lease_owner_remarks.parquet",
    "company_all": "df_company_all.parquet",
}

MIN_REQUIRED_DATASETS = [
    "boreholes",
    "war_main",
    "war_text",
    "points",
    "azimuth",
    "production",
    "frs",
]

INCIDENT_TERMS = {
    "stuck-pipe": [
        "stuck pipe",
        "stuck drill pipe",
        "stuck bha",
        "stuck string",
        "jarred",
        "fishing",
        "washover",
        "overshot",
    ],
    "lost-circulation": ["lost circulation", "losses", "lost returns", "lc material", "lcm", "seepage loss"],
    "kick": ["kick", "well control", "flow check", "shut in", "sidpp", "sicp"],
    "fishing": ["fish", "fishing", "overshot", "spear", "junk basket", "washover", "milling"],
    "cementing": ["cement", "squeeze", "plug", "shoe test", "liner test"],
    "logging": ["wireline", "mwd", "lwd", "log", "gamma ray", "resistivity"],
}

PRODUCTION_GROUP_ALIASES = {
    "completion_name": ("completion_name", "Completion Name"),
    "completion": ("completion_name", "Completion Name"),
    "product_code": ("product_code", "Product Code"),
    "product": ("product_code", "Product Code"),
    "production_interval_code": ("production_interval_code", "Production Interval Code"),
    "interval_code": ("production_interval_code", "Production Interval Code"),
    "interval": ("production_interval_code", "Production Interval Code"),
    "interval_code_name": ("production_interval_code", "Production Interval Code"),
}

PRODUCTION_UNITS = {
    "Monthly Oil Volume": "bbl",
    "Monthly Gas Volume": "mcf",
    "Monthly Water Volume": "bbl",
    "Injection Volume": "bbl",
    "Monthly Oil Volume_m3": "m3",
    "Monthly Gas Volume_mcf": "mcf",
    "Monthly Gas Volume_m3": "m3",
    "Monthly Water Volume_m3": "m3",
    "Injection Volume_m3": "m3",
    "Days On Prod": "days",
    "oil_volume": "bbl",
    "gas_volume": "mcf",
    "water_volume": "bbl",
    "injection_volume": "bbl",
    "days_on_prod": "days",
    "oil_rate": "bbl/day",
    "gas_rate": "mcf/day",
    "water_rate": "bbl/day",
    "Day_Aver_Oil_bbl_per_day": "bbl/day",
    "Day_Aver_Water_bbl_per_day": "bbl/day",
    "Day_Aver_Gas_mcf_per_day": "mcf/day",
    "Day_Aver_Oil": "bbl/day",
    "Day_Aver_Water": "bbl/day",
    "Day_Aver_Gas": "mcf/day",
}

PRODUCTION_TIME_SERIES_METRICS = [
    {"field": "oil_volume", "source_column": "Monthly Oil Volume", "aggregation": "sum", "unit": "bbl"},
    {"field": "gas_volume", "source_column": "Monthly Gas Volume", "aggregation": "sum", "unit": "mcf"},
    {"field": "water_volume", "source_column": "Monthly Water Volume", "aggregation": "sum", "unit": "bbl"},
    {"field": "injection_volume", "source_column": "Injection Volume", "aggregation": "sum", "unit": "bbl"},
    {"field": "days_on_prod", "source_column": "Days On Prod", "aggregation": "sum", "unit": "days"},
    {
        "field": "oil_rate",
        "source_column": "Monthly Oil Volume / Days On Prod",
        "aggregation": "derived",
        "unit": "bbl/day",
    },
    {
        "field": "gas_rate",
        "source_column": "Monthly Gas Volume / Days On Prod",
        "aggregation": "derived",
        "unit": "mcf/day",
    },
    {
        "field": "water_rate",
        "source_column": "Monthly Water Volume / Days On Prod",
        "aggregation": "derived",
        "unit": "bbl/day",
    },
]

BOREHOLE_UNITS = {
    "BH_TOTAL_MD": "ft",
    "BH_TOTAL_MD_M": "m",
    "WELL_BORE_TVD": "ft",
    "WELL_BORE_TVD_M": "m",
    "WELL_TD_SS": "ft",
    "WATER_DEPTH": "ft",
    "WATER_DEPTH_M": "m",
    "RKB_ELEVATION": "ft",
    "RKB_ELEVATION_M": "m",
    "SURF_LATITUDE": "deg",
    "SURF_LONGITUDE": "deg",
    "BOTM_LATITUDE": "deg",
    "BOTM_LONGITUDE": "deg",
}

TRAJECTORY_UNITS = {
    "Survey Point MD": "ft",
    "Survey Point TVD": "ft",
    "Survey Point neg TVD": "ft",
    "Delta X": "ft",
    "Delta Y": "ft",
    "easting": "ft Web Mercator legacy alias",
    "northing": "ft Web Mercator legacy alias",
    "webmerc_easting_ft": "ft Web Mercator",
    "webmerc_northing_ft": "ft Web Mercator",
    "Latitude": "deg",
    "Longitude": "deg",
    "Incl Ang Deg Val": "deg",
    "Incl Ang Min Val": "arcmin",
    "Dir Deg Val": "deg",
    "Dir Mins Val": "arcmin",
    "horizontal_distance_ft": "ft",
    "first_tvd_ft": "ft",
    "final_tvd_ft": "ft",
    "tvd_delta_ft": "ft",
    "delta_easting_ft": "ft",
    "delta_northing_ft": "ft",
    "coordinate_basis": "text",
}

WELLPATH_METRICS_UNITS = {
    "source_horizontal_distance_ft": "ft",
    "source_endpoint_east_offset_ft": "ft",
    "source_endpoint_north_offset_ft": "ft",
    "source_closure_azimuth_deg": "deg",
    "source_max_horizontal_departure_ft": "ft",
    "source_max_departure_md": "ft",
    "source_md_delta_ft": "ft",
    "source_tvd_delta_ft": "ft",
    "source_horizontal_tvd_ratio": "ratio",
    "source_min_md_spacing_ft": "ft",
    "source_median_md_spacing_ft": "ft",
    "calc_horizontal_distance_ft": "ft",
    "calc_endpoint_east_offset_ft": "ft",
    "calc_endpoint_north_offset_ft": "ft",
    "calc_closure_azimuth_deg": "deg",
    "calc_max_horizontal_departure_ft": "ft",
    "calc_max_departure_md": "ft",
    "calc_md_delta_ft": "ft",
    "calc_tvd_delta_ft": "ft",
    "calc_horizontal_tvd_ratio": "ratio",
    "calc_min_md_spacing_ft": "ft",
    "calc_median_md_spacing_ft": "ft",
    "calc_max_inclination_deg": "deg",
    "calc_avg_inclination_deg": "deg",
    "calc_final_inclination_deg": "deg",
    "calc_first_md_over_60deg": "ft",
    "calc_first_md_over_80deg": "ft",
    "calc_lateral_length_over_80deg_ft": "ft",
    "calc_max_dls_deg_per_100ft": "deg/100ft",
    "calc_avg_dls_deg_per_100ft": "deg/100ft",
    "calc_p95_dls_deg_per_100ft": "deg/100ft",
    "calc_cumulative_dogleg_deg": "deg",
    "horizontal_distance_diff_ft": "ft",
    "source_calc_hd_diff_pct": "pct",
    "horizontal_tvd_ratio_diff": "ratio",
    "source_first_md": "ft",
    "source_last_md": "ft",
    "calc_first_md": "ft",
    "calc_last_md": "ft",
}

AZIMUTH_DLS_UNITS = {
    "MD": "ft",
    "Deviation Angle": "deg",
    "Azimuth": "deg",
    "DLS": "deg/100ft",
    "MD_Diff": "ft",
    "min_step_ft": "ft",
    "max_deviation_deg": "deg",
    "max_dls_deg_per_100ft": "deg/100ft",
    "avg_dls_deg_per_100ft": "deg/100ft",
    "calculated_horizontal_distance_ft": "ft",
    "calculated_final_tvd_ft": "ft",
    "Calc_TVD_ft": "ft",
    "Calc_Easting_offset_ft": "ft",
    "Calc_Northing_offset_ft": "ft",
}

EARTH_RADIUS_FT = 6378137 * 3.28084

CASING_UNITS = {
    "CASING_SIZE": "in",
    "CASING_WEIGHT": "lb/ft",
    "CSNG_HOLESIZE": "in",
    "CSNG_HOLE_SIZE": "in",
    "CSNG_BOP_STACK_SIZE": "in",
    "CSNG_TOP_MD": "ft",
    "CASING_SECTION_MD": "ft",
    "CASING_SECTION_TVD": "ft",
    "CSNG_SETTING_TOP_MD": "ft",
    "CSNG_SETTING_BOTM_MD": "ft",
    "TOP_MD": "ft",
    "BOTTOM_MD": "ft",
    "CASING_BURST_PSI": "psi",
    "CASING_COLLPSE_PSI": "psi",
    "CSNG_LINER_TEST_PRSS": "psi",
    "CSNG_SHOE_TEST_PRSS": "psi",
    "CSNG_WELLHEAD_RATING": "psi",
    "CSNG_ANNULAR_RATING": "psi",
    "CSNG_BOP_RATING": "psi",
    "CSNG_ANNULAR_TEST_PRSS": "psi",
    "CSNG_BOP_DIV_TEST_PRSS": "psi",
    "CSNG_FORMATION_TEST_PRSS": "psi",
    "CSNG_MUD_WGT_PPG": "ppg",
    "CSNG_FRAC_GRAD_PPG": "ppg",
    "CASING_PORE_PRSS_PPG": "ppg",
    "CSNG_CEMENT_VOL": "bbl",
    "max_size": "in",
    "max_depth": "ft",
    "apd_max_depth_ft": "ft",
    "war_max_depth_ft": "ft",
    "max_depth_ft": "ft",
}

BHP_UNITS = {
    "BHTST_MD": "ft",
    "BHTST_TVD": "ft",
    "BHTST_PRESSURE": "psi",
    "BHTST_SI_PRSS": "psi",
    "BHTST_TEMP": "degF",
    "SI_TIME": "hr",
}

EOR_INTERVAL_UNITS = {
    "TOP_MD": "ft",
    "PERF_TOP_MD": "ft",
    "PERF_BASE_MD": "ft",
    "PERF_TOP_TVD": "ft",
    "PERF_BOTM_TVD": "ft",
    "deepest_marker_ft": "ft",
}

DECOM_UNITS = {
    "P50_COST": "USD",
    "P70_COST": "USD",
    "P90_COST": "USD",
    "DTR_COST": "USD",
    "WELL_INST_DCOM_P50": "USD",
    "WELL_INST_DCOM_P70": "USD",
    "WELL_INST_DCOM_P90": "USD",
    "WELL_INST_DCOM_INDTR": "USD",
    "WELL_PRP_DCOM_P50": "USD",
    "WELL_PRP_DCOM_P70": "USD",
    "WELL_PRP_DCOM_P90": "USD",
    "WELL_PRP_DCOM_INDTR": "USD",
    "BLK_MAX_WTR_DPTH": "ft",
}

LEASE_UNITS = {
    "ASSIGNMENT_PCT": "pct",
    "Ownership %": "pct",
    "ROYALTY_RATE": "pct",
    "ALIQUOT_AREA": "area as reported by BSEE",
    "CURRENT_AREA": "area as reported by BSEE",
}

TABLE_UNITS = {
    "boreholes": BOREHOLE_UNITS,
    "production": PRODUCTION_UNITS,
    "points": TRAJECTORY_UNITS,
    "azimuth": AZIMUTH_DLS_UNITS,
    "wellpath_metrics": WELLPATH_METRICS_UNITS,
    "bhp": BHP_UNITS,
    "eor_geomarkers": EOR_INTERVAL_UNITS,
    "eor_perf": EOR_INTERVAL_UNITS,
    "apd_casing_intervals": CASING_UNITS,
    "apd_casing_sections": CASING_UNITS,
    "war_tubular": CASING_UNITS,
    "war_tubular_prop": CASING_UNITS,
    "decom_estimates": DECOM_UNITS,
    "decom_spud_well": DECOM_UNITS,
    "decom_totals": DECOM_UNITS,
    "lease_data": LEASE_UNITS,
    "lease_owner": LEASE_UNITS,
    "lease_owner_designated_operator": LEASE_UNITS,
    "lease_owner_remarks": LEASE_UNITS,
}

METRIC_ALIASES = {
    "boreholes": {
        "total_depth": "BH_TOTAL_MD",
        "measured_depth": "BH_TOTAL_MD",
        "tvd": "WELL_BORE_TVD",
        "water_depth": "WATER_DEPTH",
    },
    "production": {
        "production_oil": "Monthly Oil Volume",
        "oil_volume": "Monthly Oil Volume",
        "production_gas": "Monthly Gas Volume",
        "gas_volume": "Monthly Gas Volume",
        "production_water": "Monthly Water Volume",
        "water_volume": "Monthly Water Volume",
        "days_on_prod": "Days On Prod",
    },
    "wellpath_metrics": {
        "horizontal_departure": "calc_max_horizontal_departure_ft",
        "max_horizontal_departure": "calc_max_horizontal_departure_ft",
        "horizontal_distance": "calc_horizontal_distance_ft",
        "source_horizontal_departure": "source_max_horizontal_departure_ft",
        "source_horizontal_distance": "source_horizontal_distance_ft",
        "lateral_length": "calc_lateral_length_over_80deg_ft",
        "max_dls": "calc_max_dls_deg_per_100ft",
        "avg_dls": "calc_avg_dls_deg_per_100ft",
        "trajectory_type": "calc_trajectory_type",
        "closure_azimuth": "calc_closure_azimuth_deg",
        "max_inclination": "calc_max_inclination_deg",
    },
    "decom_spud_well": {
        "decom_cost": "WELL_INST_DCOM_P90",
        "p50_cost": "WELL_INST_DCOM_P50",
        "p70_cost": "WELL_INST_DCOM_P70",
        "p90_cost": "WELL_INST_DCOM_P90",
    },
    "decom_totals": {
        "decom_cost": "P90_COST",
        "p50_cost": "P50_COST",
        "p70_cost": "P70_COST",
        "p90_cost": "P90_COST",
    },
    "lease_data": {
        "royalty_rate": "ROYALTY_RATE",
        "current_area": "CURRENT_AREA",
    },
    "lease_owner": {
        "assignment_pct": "ASSIGNMENT_PCT",
        "ownership_pct": "ASSIGNMENT_PCT",
        "owner_percent": "ASSIGNMENT_PCT",
        "interest_pct": "ASSIGNMENT_PCT",
    },
    "lease_owner_designated_operator": {
        "assignment_pct": "ASSIGNMENT_PCT",
        "ownership_pct": "ASSIGNMENT_PCT",
        "owner_percent": "ASSIGNMENT_PCT",
        "interest_pct": "ASSIGNMENT_PCT",
    },
    "lease_owner_remarks": {
        "assignment_pct": "ASSIGNMENT_PCT",
        "ownership_pct": "ASSIGNMENT_PCT",
        "owner_percent": "ASSIGNMENT_PCT",
        "interest_pct": "ASSIGNMENT_PCT",
    },
}
